require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Shae' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  ## Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  
  pod 'react-native-camera', :subspecs => ['RCT', 'RN', 'FaceDetectorMLKit'], :path => '../node_modules/react-native-camera'

  pod 'Firebase/MLVision', '6.25.0'
  # If you want to detect face contours (landmark detection and classification
  # don't require this additional model):
  pod 'Firebase/MLVisionFaceModel', '6.25.0'


  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  target 'ShaeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
  
  use_native_modules!
end

target 'Shae-tvOS' do
  # Pods for Shae-tvOS

  target 'Shae-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
