let defaultImagePath = '../resources/';
let defaultIconPath = '../resources/icon/';

const Icons = {
    InformationIcon: require(`${defaultIconPath}information_Icon.png`),
    BackIcon: require(`${defaultIconPath}back.png`),
    TickCheckIcon: require(`${defaultIconPath}tick_check.png`),
    PlayIcon: require(`${defaultIconPath}play.png`),
    FitnessImg: require(`${defaultIconPath}coachFitness.png`),
    DealingFoodImg: require(`${defaultImagePath}dealing_food.png`),
    JuicesImg: require(`${defaultImagePath}juices.png`),
    SensorImg: require(`${defaultImagePath}sensor.png`),
    SimpleFoodImg: require(`${defaultImagePath}simple_food.png`),
    SquareCheckIcon: require(`${defaultIconPath}square_check.png`),
    SquareUnCheckIcon: require(`${defaultIconPath}square_uncheck.png`),
    CloseIcon: require(`${defaultIconPath}close.png`),
    InfoIcon: require(`${defaultIconPath}info.png`),
    MealDishesIcon: require(`${defaultImagePath}meal_dishes.png`),
    MealDishes1Icon: require(`${defaultImagePath}meal_dishes1.png`),
    TrackMeasurementsIcon: require(`${defaultIconPath}track_measurements.png`),
    FeelingIcon: require(`${defaultIconPath}feeling.png`),
    ArrowGrayRightIcon: require(`${defaultIconPath}rightArrow.png`),
    EatLunchIcon: require(`${defaultIconPath}eat.png`),
    FuelIcon: require(`${defaultIconPath}fuel.png`),
    MoveManIcon: require(`${defaultIconPath}move.png`),
    SnackAppleIcon: require(`${defaultIconPath}snackapple.png`),
    MoonStarsIcon: require(`${defaultIconPath}moon_stars.png`),
    PlayBlueIcon: require(`${defaultIconPath}play_blue.png`),
    CloudIcon: require(`${defaultIconPath}cloud.png`),
    ContactIcon: require(`${defaultIconPath}contact.png`),
    measurement: require(`${defaultIconPath}measurement.png`),
    CalendarIcon: require(`${defaultIconPath}calendar.png`),
    PartyIcon: require(`${defaultIconPath}party.png`),
    ClockTimeIcon: require(`${defaultIconPath}clocktime.png`),
    Detox1Img: require(`${defaultImagePath}detox1.png`),
    Detox2Img: require(`${defaultImagePath}detox2.png`),
    Detox3Img: require(`${defaultImagePath}detox3.png`),
    Detox4Img: require(`${defaultImagePath}detox4.png`),
    Detox5Img: require(`${defaultImagePath}detox5.png`),
    Detox6Img: require(`${defaultImagePath}detox6.png`),
    Calendar1Icon: require(`${defaultIconPath}calendar1.png`),
    EssenseIcon: require(`${defaultIconPath}essense.png`),
    LeafsIcon: require(`${defaultIconPath}leafs.png`),
    TipsIcon: require(`${defaultIconPath}tips.png`),
    OptimizeIcon: require(`${defaultIconPath}optimize.png`),
    AfterJourneyImg: require(`${defaultImagePath}afterjourney.png`),
    BeforeJourneyImg: require(`${defaultImagePath}beforejourney.png`),
    FacebookIcon: require(`${defaultIconPath}facebook.png`),
    InstagramIcon: require(`${defaultIconPath}instagram.png`),
    TwitterIcon: require(`${defaultIconPath}twitter.png`),
    ArrowDownIcon: require(`${defaultIconPath}arrowDown.png`),
    ArrowUpIcon: require(`${defaultIconPath}arrowUp.png`),
    ArrowLeftIcon: require(`${defaultIconPath}arrowLeft.png`),
    ArrowRightIcon: require(`${defaultIconPath}arrowRight.png`),
};

export default Icons;